version: '3.8'

services:
  senzory-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mariadb  # Use the service name for the database host
      DB_USER: dcuk_user
      DB_PASSWORD: dcuk  # Add DB_PASSWORD if needed
      DB_NAME: dcuk_mqtt_docker
